[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
repository = "https://github.com/unexcellent/facade-tile-seg"

[tool.poetry.dependencies]
python = ">=3.10, <3.14"
kagglehub = "0.4.0"
torch = "2.9.1"
pillow = "12.1.0"
torchvision = "0.24.1"
requests = "^2.32.5"
lightning = "^2.6.1"

[tool.poetry.group.dev.dependencies]
mypy-extensions = "<2.0"
ruff = "<1.0"
types-requests = "^2.32.4.20260107"

[tool.poetry.group.test.dependencies]
pytest = "<9.0"
pytest_benchmark = "<6.0"

[tool.ruff]
exclude = ["sandbox/*"]
line-length = 101

[tool.ruff.lint]
exclude = ["test/*"]
select = ["ALL"]
ignore = [
    "COM812", # conflicts with ruff formatter

    "D100", # imo no docstrings are necessary in public modules
    "D105", # imo magic methods are self explanatory
    "D107", # __init__ docstrings are not necessary
    "D203", # incompatible with D211
    "D213", # incompatible with D212

    "EM102", # specifying custom exceptions is not necessary for this project

    "FBT001", # boolean args are a great way to change the behavior of a function
    "FBT002", # boolean args are a great way to change the behavior of a function

    "ISC001", # conflicts with ruff formatter

    "N802", # mixed case is necessary for including units in the function names
    "N803", # mixed case is necessary for including units in the argument names
    "N806", # mixed case is necessary for including units in the argument names
    "N815", # mixed case is necessary for including units in the variable names

    "T201",  # sometimes you want to have console output
    "TC001", # adds hard to understand compexity without providing a benefit for smaller projects
    "TC002", # same as TCH001
    "TC003", # same as TCH001

    "TRY003", # specifying custom exceptions is not necessary for this project

    "SIM103", # less readable in some cases imo
]

[tool.mypy]
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_unreachable = true
python_version = "3.12"
ignore_missing_imports = true
disable_error_code = ["call-arg", "import-untyped"]

[tool.pytest.ini_options]
python_functions = ["test_*", "bench_*"]
python_files = ["test_*.py"]
testpaths = ["test", "benchmarking"]
xfail_strict = true
